name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  quality:
    name: Code Quality & Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7.33.7

      - name: Install dependencies
        run: pnpm install

      - name: Run format check
        run: pnpm format:check

      - name: Run lint
        run: pnpm lint

      - name: Run secretlint
        run: pnpm secretlint

      - name: Run tests
        run: pnpm test

      - name: Build project
        run: pnpm build

      - name: Check build artifacts
        run: |
          test -f dist/index.js
          test -f dist/index.mjs
          test -f dist/index.d.ts
          test -f dist/index.d.mts