name: Release

on:
  release:
    types: [created]

jobs:
  publish:
    name: Publish to NPM
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7.33.7

      - name: Install dependencies
        run: pnpm install

      - name: Run quality checks
        run: |
          pnpm format:check
          pnpm lint
          pnpm secretlint
          pnpm test

      - name: Build project
        run: pnpm build

      - name: Update package version from release tag
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          VERSION=${VERSION#v}
          npm version $VERSION --no-git-tag-version
          echo "Updated package.json version to $VERSION"

      - name: Publish to npm
        run: pnpm publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create release comment
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const releaseId = context.payload.release.id;
            
            await github.rest.repos.updateRelease({
              owner,
              repo,
              release_id: releaseId,
              body: context.payload.release.body + '\n\n🚀 Published to npm: https://www.npmjs.com/package/ai-rules'
            });